Add support for pre-ochtra
In case you want to preserve pre-commit hooks for code style
other other hooks that are not strictly about syntax errors.

Just rename your current pre-commit to pre-ochtra, then isntall
ochtra

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -6,19 +6,21 @@
 # Can be 'installed globally' as of Git 1.7.1 using init.templatedir
 #
 # Copyright 2013, kvz (http://twitter.com/kvz)
-#
-# Necessary check for initial commit
-against="4b825dc642cb6eb9a060e54bf8d69288fbee4904"
-git rev-parse --verify HEAD >/dev/null 2>&1 && against="HEAD"
 
-# Only run when we're on a branch (to avoid rebase hell)
-# http://git-blame.blogspot.nl/2013/06/checking-current-branch-programatically.html
-# --short is not supported on older git versions so using awk here
-if branch=$(git symbolic-ref -q HEAD |awk -F/ '{print $NF}'); then
-  echo on branch $branch
-else
-  echo not on any branch
-  exit 0
+set -o pipefail
+set -o errexit
+set -o nounset
+# set -o xtrace
+__DIR__="$(cd "$(dirname "${0}")"; echo $(pwd))"
+__BASE__="$(basename "${0}")"
+__FILE__="${__DIR__}/${__BASE__}"
+
+if [ -x "${__DIR__}/pre-ochtra" ]; then
+  echo "Running pre-ochtra"
+  if ! ${__DIR__}/pre-ochtra; then
+    echo "pre-ochtra failed"
+    exit 1
+  fi
 fi
 
 # Takes a command as arguments and paints both it's STDOUT & STDERR in
@@ -38,6 +40,20 @@ function paint() (
   ("${@:3}" 2>&1>&3 |sed ${stderr} >&2) 3>&1 \
                     |sed ${stdout}
 )
+
+# Necessary check for initial commit
+against="4b825dc642cb6eb9a060e54bf8d69288fbee4904"
+git rev-parse --verify HEAD >/dev/null 2>&1 && against="HEAD"
+
+# Only run when we're on a branch (to avoid rebase hell)
+# http://git-blame.blogspot.nl/2013/06/checking-current-branch-programatically.html
+# --short is not supported on older git versions so using awk here
+if branch=$(git symbolic-ref -q HEAD |awk -F/ '{print $NF}'); then
+  echo on branch $branch
+else
+  echo not on any branch
+  exit 0
+fi
 
 # (A)dded (C)opied or (M)odified
 git diff-index --cached --full-index --diff-filter=ACM $against |while read -r line; do
